RUN_NAME: exp038
RUN_DESC: deberta-v3-xsmall searching folds best
globals:
  fold: null
  seed: 42
  n_fold: 15
  work_dir: /workspaces/us-patent-phrase-to-phrase-matching/work
  input_dir: ../input/us-patent-phrase-to-phrase-matching
  input_cpc_dir: ../input/cpc-data
  input_nltk_dir: ../input/nltk-downloads
  input_huggingface_dir: ../input/huggingface-models
  debug: false
training:
  device: cuda
  use_amp: true
  benchmark: false
  deterministic: true
  max_epochs: 10
  max_grad_norm: 10.0
  accumulate_gradient_batchs: 1
  steps_per_epoch:
    type: integer_div_ceil
    x:
      type: __len__
      obj: '@/dataloader/train'
    'y': '@/training/accumulate_gradient_batchs'
mlflow:
  save_dir: ../mlruns
  experiment_name: experiments
  save_results: true
model_encoder_name: microsoft/deberta-v3-xsmall
model_filename:
  type: str_concat
  ls:
  - model_
  - '@/model/encoder_name/'
  - _fold
  - '@/globals/fold'
  - .pth
model:
  type: Model
  encoder_name:
    type: get_encoder_name
    path: '@/model_encoder_name'
  encoder_path:
    type: path_join
    ls:
    - '@/globals/input_huggingface_dir'
    - '@/model_encoder_name'
  encoder_params:
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
  embedding_length:
    type: __len__
    obj: '@/tokenizer'
  head_type: SimpleHead
  head_params:
    out_features: 1
    dropout_rate: 0.1
tokenizer:
  type: get_tokenizer
  tokenizer_path: '@/model/encoder_path'
  tokenizer_params: {}
preprocessor:
  type: Preprocessor
  input_nltk_dir: '@/globals/input_nltk_dir'
dataset:
  max_length: 256
  train:
    type: Dataset
    df: null
    tokenizer: '@/tokenizer'
    max_length: '@/dataset/max_length'
    input_cpc_dir: '@/globals/input_cpc_dir'
    input_nltk_dir: '@/globals/input_nltk_dir'
  valid:
    type: Dataset
    df: null
    tokenizer: '@/tokenizer'
    max_length: '@/dataset/max_length'
    input_cpc_dir: '@/globals/input_cpc_dir'
    input_nltk_dir: '@/globals/input_nltk_dir'
  test:
    type: Dataset
    df: null
    tokenizer: '@/tokenizer'
    max_length: '@/dataset/max_length'
    input_cpc_dir: '@/globals/input_cpc_dir'
    input_nltk_dir: '@/globals/input_nltk_dir'
dataloader:
  train:
    type: DataLoader
    dataset: '@/dataset/train'
    batch_size: 32
    num_workers: 2
    shuffle: true
    pin_memory: true
    drop_last: true
    collate_fn:
      type: Collate
      tokenizer: '@/tokenizer'
  valid:
    type: DataLoader
    dataset: '@/dataset/valid'
    batch_size: 16
    num_workers: 2
    shuffle: false
    pin_memory: false
    drop_last: false
    collate_fn:
      type: Collate
      tokenizer: '@/tokenizer'
  test:
    type: DataLoader
    dataset: '@/dataset/test'
    batch_size: 16
    num_workers: 1
    shuffle: false
    pin_memory: false
    drop_last: false
    collate_fn:
      type: Collate
      tokenizer: '@/tokenizer'
optimizer:
  type: AdamW
  params:
    type: get_optimizer_params
    model: '@/model'
    encoder_lr: 1.0e-05
    head_lr: 1.0e-05
    weight_decay: 0.0
scheduler:
  type: OneCycleLR
  optimizer: '@/optimizer'
  max_lr:
  - 5.0e-05
  - 5.0e-05
  - 5.0e-05
  pct_start: 0.1
  steps_per_epoch: '@/training/steps_per_epoch'
  epochs: '@/training/max_epochs'
  anneal_strategy: cos
  div_factor: 100.0
  final_div_factor: 1
  verbose: false
loss:
  type: MSELoss
metric:
  mse_loss:
    type: MSEMetric
    compute_on_step: false
  bce_loss:
    type: BCEMetric
    compute_on_step: false
  metric:
    type: PearsonCorrCoefMetric
    compute_on_step: false
manager:
  type: ExtensionsManager
  models: '@/model'
  optimizers: '@/optimizer'
  max_epochs: '@/training/max_epochs'
  iters_per_epoch:
    type: __len__
    obj: '@/dataloader/train'
  out_dir: '@/globals/work_dir'
extensions:
- extension:
    type: snapshot
    target: '@/model'
    n_retains: 1
    filename: '@/model_filename'
  trigger:
    type: MaxValueTrigger
    key: valid/metric
    trigger:
    - 1
    - epoch
- extension:
    type: observe_lr
    optimizer: '@/optimizer'
  trigger:
    type: IntervalTrigger
    period: 1
    unit: iteration
- extension:
    type: LogReport
    filename:
      type: str_concat
      ls:
      - log_fold
      - '@/globals/fold'
  trigger:
    type: IntervalTrigger
    period: 1
    unit: epoch
- extension:
    type: PlotReport
    y_keys: lr
    x_key: iteration
    filename:
      type: str_concat
      ls:
      - lr_fold
      - '@/globals/fold'
      - .png
  trigger:
    type: IntervalTrigger
    period: 1
    unit: epoch
- extension:
    type: PlotReport
    y_keys:
    - valid/mse_loss
    x_key: epoch
    filename:
      type: str_concat
      ls:
      - mse_loss_fold
      - '@/globals/fold'
      - .png
  trigger:
    type: IntervalTrigger
    period: 1
    unit: epoch
- extension:
    type: PlotReport
    y_keys:
    - valid/bce_loss
    x_key: epoch
    filename:
      type: str_concat
      ls:
      - bce_loss_fold
      - '@/globals/fold'
      - .png
  trigger:
    type: IntervalTrigger
    period: 1
    unit: epoch
- extension:
    type: PlotReport
    y_keys:
    - valid/metric
    x_key: epoch
    filename:
      type: str_concat
      ls:
      - metrics_fold
      - '@/globals/fold'
      - .png
  trigger:
    type: IntervalTrigger
    period: 1
    unit: epoch
- extension:
    type: PrintReport
    entries:
    - epoch
    - iteration
    - lr
    - loss
    - valid/mse_loss
    - valid/bce_loss
    - valid/metric
    - elapsed_time
  trigger:
    type: IntervalTrigger
    period: 1
    unit: epoch
- extension:
    type: ProgressBar
    update_interval: 1
  trigger:
    type: IntervalTrigger
    period: 1
    unit: iteration
- extension:
    type: Evaluator
    loader: '@/dataloader/valid'
    prefix: valid/
    model: '@/model'
    metrics: '@/metric'
    device: '@/training/device'
  trigger:
    type: IntervalTrigger
    period: 1
    unit: epoch
